### ISSUE TITLE
BUG : Failed to fetch server config for writeKey

### ISSUE THREAD

**Issue by doubler12138** [rudderlabs/rudder-sdk-react-native#204] opened 2023-04-12 05:16 UTC
The error occurring on: Android

in file RudderServerConfigManager.java line: 100
httpConnection.setRequestProperty("Authorization", "Basic " + Base64.encodeToString((_writeKey + ":").getBytes("UTF-8"), Base64.DEFAULT));

use encode flag by Base64.DEFAULT will cause add 0x0a in the end of encoded string

And it will cause
<img width="567" alt="image" src="https://user-images.githubusercontent.com/32301297/231356522-7ed00ff2-ff73-4b3f-b8c6-0ac5f84ad793.png">

Please modify the use of flag to Base64.NO_WARP

**Comment by doubler12138** [comment] 2023-04-12 14:21
Yes, I confirm that there is no problem with my writeKey. I can send events from my iOS device with the same key.
<img width="519" alt="image" src="https://user-images.githubusercontent.com/32301297/231487383-84851b98-8d81-4101-b23b-ddf403e714fc.png">

**Comment by doubler12138** [comment] 2023-04-12 14:25
And here is my build.gradle
<img width="686" alt="image" src="https://user-images.githubusercontent.com/32301297/231488491-2ffbda38-4783-455d-91a6-f9fdf094ac8f.png">

**Comment by 1abhishekpandey** [comment] 2023-04-12 14:30
Can you please share your `writeKey` by joining our [Slack channel](https://join.slack.com/share/enQtNTA5NTY0MzU3MTE3My00MmZiMWQwYzRhY2JjMmY4OTAxZmQ3NTM0OTY1ZDJiY2Y0ZjAwNmMxZTg1ZjAyMTIzMTczYmIwNTY0MGUzNGIz).

**Comment by 1abhishekpandey** [comment] 2023-04-12 15:34
I used the `writeKey` you provided but was unable to reproduce the issue.
In our case, Android SDK is working properly with the provided writeKey.
We'll look into this further and keep you updated.

I'm not sure, if this scenario has caused this issue or not but wanted to confirm once, are you using any `ProGuard` rules in your Android app?

**Comment by 1abhishekpandey** [comment] 2023-04-13 06:13
@doubler12138 Can you please let us know if this issue occurs on other real Android devices or emulators, or if it is specific to certain devices?

**Comment by 1abhishekpandey** [comment] 2023-04-20 05:54
Hey @doubler12138, please let us know if the issue still persists.

**Comment by 1abhishekpandey** [comment] 2023-04-25 12:22
@doubler12138 Can you please let us know the following details:

- What is the JDK version being used for the Android project?
- Details of your actual Android device:
      - OS version (e.g., Android 12, Android 11)
      - Device name (e.g., Samsung Galaxy S21, Google Pixel 6)
      - Device model (e.g., SM-G998B)
- Does it throws that error on any emulator or not?
- Have you checked if this issue is specific to a particular Android device/version?

Also, you're currently on version `1.5.2` of the Rudder-Android SDK, can you please update to the latest version `1.13.0` and check again if the issue persists?

**Comment by doubler12138** [comment] 2023-04-26 08:22
JDK Version is 11.0.15, OS version is 10, Device Name is Galaxy A9s, Device model is SM-A9200，it also throws the same error in emulator. And I also modified package.json and build.gradle to upgrade the versions of "@rudderstack/rudder-sdk-react-native" and "com.rudderstack.android.sdk:core" to 1.7.0 and 1.13.0. It still has the same error

**Comment by doubler12138** [comment] 2023-04-26 08:22
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/32301297/234515165-34abda1f-4f6b-43c0-8565-45e856aeae07.png">

**Comment by itsdebs** [comment] 2023-04-28 12:36
@doubler12138 We are considering the fix for next release, but our writekeys are never of such lengths that needs wrapping. To understand the core reason and to avoid re occurrences of similar issues in future, we would really like to reproduce the error in our end. It will be very nice of you to connect with us in slack [here](https://join.slack.com/share/enQtNTE4NDg3MDMyMTIzNC1jODkxM2QyZDk2YTZjMjNiNzg3NWFkMzM1Nzg4YTE3OWRkM2E5MTYwYjdjOTM3NTI0NjBiYTRmNTZhMzQzYzNi) and mention a time that works for you, so we can get on a call to understand the issue.

**Comment by 1abhishekpandey** [comment] 2023-05-24 06:09
Hey @doubler12138, We have addressed the issue in the latest release of Rudder React-Native version 1.7.1. To resolve the problem, please update to this version.
Refer: https://www.npmjs.com/package/@rudderstack/rudder-sdk-react-native?activeTab=versions

**Comment by 1abhishekpandey** [comment] 2023-05-29 00:07
We are closing this issue, as the fix has already been provided. Feel free to reopen it, in case there is an issue.

**Closed by 1abhishekpandey** 2023-05-29 00:07 UTC
Labels: bug
