### ISSUE TITLE
BUG : Unable to compile modules during release build process

### ISSUE THREAD

**Issue by eb-real** [rudderlabs/rudder-sdk-react-native#231] opened 2023-08-22 19:29 UTC
**Describe the bug**
- Unable to compile rudderstack modules during Expo release build process. It appears there is a class being used before it's imported.
- Builds started failing after 8/17.

Error as it appears in our release logs:
```
❌  (node_modules/@rudderstack/rudder-sdk-react-native/ios/RNRudderSdkModule.m:70:35)

  68 |     }
  69 |     [self->session saveEventTimestamp];
> 70 |     RSMessageBuilder* builder = [[RSMessageBuilder alloc] init];
     |                                   ^ definition of 'RSMessageBuilder' must be imported from module 'Rudder.RSMessageBuilder' before it is required
  71 |     [builder setEventName:_event];
  72 |     [builder setPropertyDict:_properties];
  73 |     [builder setRSOption:[self getRudderOptionsObject:_options]];
```

**Which platform is the issue occurring on**
Is the error occurring on:

- [ ] Android
- [x] iOS
- [ ] Both Android and iOS

**Version of the _React-Native_ SDK**
- Version: 1.8.0

**Framework version of the SDK**
- "react-native": 0.71.8

**Comment by 1abhishekpandey** [comment] 2023-08-22 20:10
Thanks for raising this issue. We will look into this and get back to you.

**Comment by eb-real** [comment] 2023-08-22 20:23
Thanks for the quick reply. Let me know if I can provide you with anything else to help troubleshoot.

**Comment by 1abhishekpandey** [comment] 2023-08-24 09:16
Hey @eb-real and @darnfish,
We have released the fix: https://github.com/rudderlabs/rudder-sdk-react-native/releases/tag/rudder-sdk-react-native%401.8.1, can you please utilise the latest version of the `rudder-sdk-react-native@1.8.1` and let us know if it solves your issue or not.

**Comment by darnfish** [comment] 2023-08-24 13:01
Thanks! All working now :~)

**Comment by eb-real** [comment] 2023-08-24 15:42
@1abhishekpandey Thanks so much! Issue is resolved on our end as well.

**Comment by eb-real** [comment] 2023-08-24 19:22
@1abhishekpandey I hate to bring this up after closing the ticket. But it looks like the original issue was resolved but a new one was introduced. I originally thought this was unrelated but based on the path it looks like it is. `...Rudder/Rudder.framework/Headers/sqlite3.h'`.

```
❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/EXUpdates/EXUpdates.framework/Headers/EXUpdatesDatabaseUtils.h:4:9)

  2 | 
  3 | #import <Foundation/Foundation.h>
> 4 | #import <sqlite3.h>
    |         ^ include of non-modular header inside framework module 'EXUpdates.EXUpdatesDatabaseUtils': '/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h'
  5 | 
  6 | NS_ASSUME_NONNULL_BEGIN
  7 | 
```

Let me know if you'd like me to open a separate issue.

**Comment by 1abhishekpandey** [comment] 2023-08-24 20:07
While we investigate this issue, could you please provide the following details:

1. Steps to reproduce the new problem.
2. The version of the Rudder iOS SDK from your Podfile.lock.
3. Confirm whether your iOS app uses Sqlite3.

Additionally, please try cleaning and rebuilding your iOS app.

**Comment by 1abhishekpandey** [comment] 2023-08-24 21:21
Hey @eb-real, 
Can you also confirm if you have `expo-updates` in your React Native project?

**Comment by 1abhishekpandey** [comment] 2023-08-24 21:31
Can you please let me know which package which uses: `EXUpdatesDatabaseUtils.h`?

**Comment by 1abhishekpandey** [comment] 2023-08-24 22:46
I suggest updating `expo` to the latest version and trying again. Please let me know if that works.

**Comment by eb-real** [comment] 2023-08-28 15:54
@1abhishekpandey Thank you for your help. We're still troubleshooting on our end but it does look related to Expo. I think we can close this issue again and I will open up a separate issue if we see anything related to Rudderstack. Thank you!

**Comment by eb-real** [comment] 2023-08-28 17:22
@1abhishekpandey We're still seeing build issues through EAS after updating to `Expo 49` + dependencies. 

- RNRudderSdk - 1.8.1
- We do not use `Sqlite3` in our app. The only reference to it is here `Compiling @rudderstack/rudder-sdk-react-native Pods/Rudder » sqlite3.c`

**Comment by 1abhishekpandey** [comment] 2023-08-28 17:39
We attempted to reproduce the same error but were unsuccessful. In our case, it's working well. 

Have you encountered the same error after updating to Expo 49? In the latest version of Expo, there is no file named `EXUpdatesDatabaseUtils.h`. They've migrated those files to the swift, refer [this](https://github.com/expo/expo/pull/21450/files).

Could you please provide a minimal viable example that can reproduce this error?

**Comment by sam1463** [comment] 2023-08-28 17:46
The new error is different. I can try to make a minimal reproducible example, but in the mean time here are the errors we're seeing now on eas build:

```
› Compiling Real » SplashScreen.storyboard


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:728:8)

  726 | */
  727 | typedef struct sqlite3_file sqlite3_file;
> 728 | struct sqlite3_file {
      |        ^ redefinition of 'sqlite3_file'
  729 |   const struct sqlite3_io_methods *pMethods;  /* Methods for an open file */
  730 | };
  731 | 


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:834:8)

  832 | */
  833 | typedef struct sqlite3_io_methods sqlite3_io_methods;
> 834 | struct sqlite3_io_methods {
      |        ^ redefinition of 'sqlite3_io_methods'
  835 |   int iVersion;
  836 |   int (*xClose)(sqlite3_file*);
  837 |   int (*xRead)(sqlite3_file*, void*, int iAmt, sqlite3_int64 iOfst);


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:1464:8)

  1462 | typedef struct sqlite3_vfs sqlite3_vfs;
  1463 | typedef void (*sqlite3_syscall_ptr)(void);
> 1464 | struct sqlite3_vfs {
       |        ^ redefinition of 'sqlite3_vfs'
  1465 |   int iVersion;            /* Structure version number (currently 3) */
  1466 |   int szOsFile;            /* Size of subclassed sqlite3_file */
  1467 |   int mxPathname;          /* Maximum file pathname length */


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:1761:8)

  1759 | */
  1760 | typedef struct sqlite3_mem_methods sqlite3_mem_methods;
> 1761 | struct sqlite3_mem_methods {
       |        ^ redefinition of 'sqlite3_mem_methods'
  1762 |   void *(*xMalloc)(int);         /* Memory allocation function */
  1763 |   void (*xFree)(void*);          /* Free a prior allocation */
  1764 |   void *(*xRealloc)(void*,int);  /* Resize an allocation */


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:3862:29)

  3860 | ** invoked prior to calling sqlite3_free_filename(Y).
  3861 | */
> 3862 | SQLITE_API sqlite3_filename sqlite3_create_filename(
       |                             ^ conflicting types for 'sqlite3_create_filename'
  3863 |   const char *zDatabase,
  3864 |   const char *zJournal,
  3865 |   const char *zWal,


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:3869:17)

  3867 |   const char **azParam
  3868 | );
> 3869 | SQLITE_API void sqlite3_free_filename(sqlite3_filename);
       |                 ^ conflicting types for 'sqlite3_free_filename'
  3870 | 
  3871 | /*
  3872 | ** CAPI3REF: Error Codes And Messages


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7132:8)

  7130 | ** any database connection.
  7131 | */
> 7132 | struct sqlite3_module {
       |        ^ redefinition of 'sqlite3_module'
  7133 |   int iVersion;
  7134 |   int (*xCreate)(sqlite3*, void *pAux,
  7135 |                int argc, const char *const*argv,


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7272:8)

  7270 | ** 3009000.
  7271 | */
> 7272 | struct sqlite3_index_info {
       |        ^ redefinition of 'sqlite3_index_info'
  7273 |   /* Inputs */
  7274 |   int nConstraint;           /* Number of entries in aConstraint */
  7275 |   struct sqlite3_index_constraint {


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7282:10)

  7280 |   } *aConstraint;            /* Table of WHERE clause constraints */
  7281 |   int nOrderBy;              /* Number of terms in the ORDER BY clause */
> 7282 |   struct sqlite3_index_orderby {
       |          ^ redefinition of 'sqlite3_index_orderby'
  7283 |      int iColumn;              /* Column number */
  7284 |      unsigned char desc;       /* True for DESC.  False for ASC. */
  7285 |   } *aOrderBy;               /* The ORDER BY clause */


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7287:10)

  7285 |   } *aOrderBy;               /* The ORDER BY clause */
  7286 |   /* Outputs */
> 7287 |   struct sqlite3_index_constraint_usage {
       |          ^ redefinition of 'sqlite3_index_constraint_usage'
  7288 |     int argvIndex;           /* if >0, constraint is part of argv to xFilter */
  7289 |     unsigned char omit;      /* Do not code a test for this constraint */
  7290 |   } *aConstraintUsage;


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7450:8)

  7448 | ** freed by sqlite3_free() and the zErrMsg field will be zeroed.
  7449 | */
> 7450 | struct sqlite3_vtab {
       |        ^ redefinition of 'sqlite3_vtab'
  7451 |   const sqlite3_module *pModule;  /* The module for this virtual table */
  7452 |   int nRef;                       /* Number of open cursors */
  7453 |   char *zErrMsg;                  /* Error message from sqlite3_mprintf() */


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7474:8)

  7472 | ** are common to all implementations.
  7473 | */
> 7474 | struct sqlite3_vtab_cursor {
       |        ^ redefinition of 'sqlite3_vtab_cursor'
  7475 |   sqlite3_vtab *pVtab;      /* Virtual table of this cursor */
  7476 |   /* Virtual table implementations will typically add additional fields */
  7477 | };


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7969:8)

  7967 | */
  7968 | typedef struct sqlite3_mutex_methods sqlite3_mutex_methods;
> 7969 | struct sqlite3_mutex_methods {
       |        ^ redefinition of 'sqlite3_mutex_methods'
  7970 |   int (*xMutexInit)(void);
  7971 |   int (*xMutexEnd)(void);
  7972 |   sqlite3_mutex *(*xMutexAlloc)(int);


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:8738:8)

  8736 | */
  8737 | typedef struct sqlite3_pcache_page sqlite3_pcache_page;
> 8738 | struct sqlite3_pcache_page {
       |        ^ redefinition of 'sqlite3_pcache_page'
  8739 |   void *pBuf;        /* The content of the page */
  8740 |   void *pExtra;      /* Extra information associated with the page */
  8741 | };


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:8903:8)

  8901 | */
  8902 | typedef struct sqlite3_pcache_methods2 sqlite3_pcache_methods2;
> 8903 | struct sqlite3_pcache_methods2 {
       |        ^ redefinition of 'sqlite3_pcache_methods2'
  8904 |   int iVersion;
  8905 |   void *pArg;
  8906 |   int (*xInit)(void*);


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:8926:8)

  8924 | */
  8925 | typedef struct sqlite3_pcache_methods sqlite3_pcache_methods;
> 8926 | struct sqlite3_pcache_methods {
       |        ^ redefinition of 'sqlite3_pcache_methods'
  8927 |   void *pArg;
  8928 |   int (*xInit)(void*);
  8929 |   void (*xShutdown)(void*);


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:10290:16)

  10288 | ** the most recent version.
  10289 | */
> 10290 | typedef struct sqlite3_snapshot {
        |                ^ redefinition of 'sqlite3_snapshot'
  10291 |   unsigned char hidden[48];
  10292 | } sqlite3_snapshot;
  10293 | 


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:10292:3)

  10290 | typedef struct sqlite3_snapshot {
  10291 |   unsigned char hidden[48];
> 10292 | } sqlite3_snapshot;
        |   ^ typedef redefinition with different types ' vs 'struct sqlite3_snapshot')
  10293 | 
  10294 | /*
  10295 | ** CAPI3REF: Record A Database Snapshot


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:728:8)

  726 | */
  727 | typedef struct sqlite3_file sqlite3_file;
> 728 | struct sqlite3_file {
      |        ^ redefinition of 'sqlite3_file'
  729 |   const struct sqlite3_io_methods *pMethods;  /* Methods for an open file */
  730 | };
  731 | 


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:834:8)

  832 | */
  833 | typedef struct sqlite3_io_methods sqlite3_io_methods;
> 834 | struct sqlite3_io_methods {
      |        ^ redefinition of 'sqlite3_io_methods'
  835 |   int iVersion;
  836 |   int (*xClose)(sqlite3_file*);
  837 |   int (*xRead)(sqlite3_file*, void*, int iAmt, sqlite3_int64 iOfst);


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:1464:8)

  1462 | typedef struct sqlite3_vfs sqlite3_vfs;
  1463 | typedef void (*sqlite3_syscall_ptr)(void);
> 1464 | struct sqlite3_vfs {
       |        ^ redefinition of 'sqlite3_vfs'
  1465 |   int iVersion;            /* Structure version number (currently 3) */
  1466 |   int szOsFile;            /* Size of subclassed sqlite3_file */
  1467 |   int mxPathname;          /* Maximum file pathname length */


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:1761:8)

  1759 | */
  1760 | typedef struct sqlite3_mem_methods sqlite3_mem_methods;
> 1761 | struct sqlite3_mem_methods {
       |        ^ redefinition of 'sqlite3_mem_methods'
  1762 |   void *(*xMalloc)(int);         /* Memory allocation function */
  1763 |   void (*xFree)(void*);          /* Free a prior allocation */
  1764 |   void *(*xRealloc)(void*,int);  /* Resize an allocation */


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:3862:29)

  3860 | ** invoked prior to calling sqlite3_free_filename(Y).
  3861 | */
> 3862 | SQLITE_API sqlite3_filename sqlite3_create_filename(
       |                             ^ conflicting types for 'sqlite3_create_filename'
  3863 |   const char *zDatabase,
  3864 |   const char *zJournal,
  3865 |   const char *zWal,


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:3869:17)

  3867 |   const char **azParam
  3868 | );
> 3869 | SQLITE_API void sqlite3_free_filename(sqlite3_filename);
       |                 ^ conflicting types for 'sqlite3_free_filename'
  3870 | 
  3871 | /*
  3872 | ** CAPI3REF: Error Codes And Messages


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7132:8)

  7130 | ** any database connection.
  7131 | */
> 7132 | struct sqlite3_module {
       |        ^ redefinition of 'sqlite3_module'
  7133 |   int iVersion;
  7134 |   int (*xCreate)(sqlite3*, void *pAux,
  7135 |                int argc, const char *const*argv,


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7272:8)

  7270 | ** 3009000.
  7271 | */
> 7272 | struct sqlite3_index_info {
       |        ^ redefinition of 'sqlite3_index_info'
  7273 |   /* Inputs */
  7274 |   int nConstraint;           /* Number of entries in aConstraint */
  7275 |   struct sqlite3_index_constraint {


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7275:10)

  7273 |   /* Inputs */
  7274 |   int nConstraint;           /* Number of entries in aConstraint */
> 7275 |   struct sqlite3_index_constraint {
       |          ^ redefinition of 'sqlite3_index_constraint'
  7276 |      int iColumn;              /* Column constrained.  -1 for ROWID */
  7277 |      unsigned char op;         /* Constraint operator */
  7278 |      unsigned char usable;     /* True if this constraint is usable */


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7282:10)

  7280 |   } *aConstraint;            /* Table of WHERE clause constraints */
  7281 |   int nOrderBy;              /* Number of terms in the ORDER BY clause */
> 7282 |   struct sqlite3_index_orderby {
       |          ^ redefinition of 'sqlite3_index_orderby'
  7283 |      int iColumn;              /* Column number */
  7284 |      unsigned char desc;       /* True for DESC.  False for ASC. */
  7285 |   } *aOrderBy;               /* The ORDER BY clause */


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7287:10)

  7285 |   } *aOrderBy;               /* The ORDER BY clause */
  7286 |   /* Outputs */
> 7287 |   struct sqlite3_index_constraint_usage {
       |          ^ redefinition of 'sqlite3_index_constraint_usage'
  7288 |     int argvIndex;           /* if >0, constraint is part of argv to xFilter */
  7289 |     unsigned char omit;      /* Do not code a test for this constraint */
  7290 |   } *aConstraintUsage;


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7450:8)

  7448 | ** freed by sqlite3_free() and the zErrMsg field will be zeroed.
  7449 | */
> 7450 | struct sqlite3_vtab {
       |        ^ redefinition of 'sqlite3_vtab'
  7451 |   const sqlite3_module *pModule;  /* The module for this virtual table */
  7452 |   int nRef;                       /* Number of open cursors */
  7453 |   char *zErrMsg;                  /* Error message from sqlite3_mprintf() */


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7474:8)

  7472 | ** are common to all implementations.
  7473 | */
> 7474 | struct sqlite3_vtab_cursor {
       |        ^ redefinition of 'sqlite3_vtab_cursor'
  7475 |   sqlite3_vtab *pVtab;      /* Virtual table of this cursor */
  7476 |   /* Virtual table implementations will typically add additional fields */
  7477 | };


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:7969:8)

  7967 | */
  7968 | typedef struct sqlite3_mutex_methods sqlite3_mutex_methods;
> 7969 | struct sqlite3_mutex_methods {
       |        ^ redefinition of 'sqlite3_mutex_methods'
  7970 |   int (*xMutexInit)(void);
  7971 |   int (*xMutexEnd)(void);
  7972 |   sqlite3_mutex *(*xMutexAlloc)(int);


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:8738:8)

  8736 | */
  8737 | typedef struct sqlite3_pcache_page sqlite3_pcache_page;
> 8738 | struct sqlite3_pcache_page {
       |        ^ redefinition of 'sqlite3_pcache_page'
  8739 |   void *pBuf;        /* The content of the page */
  8740 |   void *pExtra;      /* Extra information associated with the page */
  8741 | };


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:8903:8)

  8901 | */
  8902 | typedef struct sqlite3_pcache_methods2 sqlite3_pcache_methods2;
> 8903 | struct sqlite3_pcache_methods2 {
       |        ^ redefinition of 'sqlite3_pcache_methods2'
  8904 |   int iVersion;
  8905 |   void *pArg;
  8906 |   int (*xInit)(void*);


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:8926:8)

  8924 | */
  8925 | typedef struct sqlite3_pcache_methods sqlite3_pcache_methods;
> 8926 | struct sqlite3_pcache_methods {
       |        ^ redefinition of 'sqlite3_pcache_methods'
  8927 |   void *pArg;
  8928 |   int (*xInit)(void*);
  8929 |   void (*xShutdown)(void*);


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:10290:16)

  10288 | ** the most recent version.
  10289 | */
> 10290 | typedef struct sqlite3_snapshot {
        |                ^ redefinition of 'sqlite3_snapshot'
  10291 |   unsigned char hidden[48];
  10292 | } sqlite3_snapshot;
  10293 | 


❌  (/Users/expo/Library/Developer/Xcode/DerivedData/Real-ecpzxulzicsncnfsjzgoacqazodi/Build/Intermediates.noindex/ArchiveIntermediates/Real/BuildProductsPath/Release-iphoneos/Rudder/Rudder.framework/Headers/sqlite3.h:10292:3)

  10290 | typedef struct sqlite3_snapshot {
  10291 |   unsigned char hidden[48];
> 10292 | } sqlite3_snapshot;
        |   ^ typedef redefinition with different types ' vs 'struct sqlite3_snapshot')
  10293 | 
  10294 | /*
  10295 | ** CAPI3REF: Record A Database Snapshot
```

**Comment by 1abhishekpandey** [comment] 2023-08-29 10:21
While you're working on providing the minimal reproducible example, could you please run the following command: `pod deintegrate && rm Podfile.lock && pod install`? Check if this resolves the issue.

Additionally, please inspect your `Podfile.lock` to check if you have `SQLite.swift` installed, and if so, note its version and let us know.

Also, try updating `SQLite.swift` to the latest version `0.14.1`, if it's not already.
In our case, I tested `SQLite.swift` with version `0.12.2`, and it produced an issue similar to what you provided in your last message. However, updating `SQLite.swift` to the latest version `0.14.1` successfully resolved the build issue. 

I believe this error is caused by `SQLite.swift`, refer to this: https://github.com/stephencelis/SQLite.swift/issues/999.

If none of these solutions works, please consider providing a minimal reproducible example.

**Comment by sam1463** [comment] 2023-08-29 13:05
Yep, not sure exactly which, but I think you're right and one of our dependencies was probably specifying an old version of SQLite. After updating most if not all of our dependencies, I don't see this issue any more, and it wasn't the same issue as this gh issue anyways. So good to close this issue. Thanks for your help!

**Closed** 2023-08-30 06:17 UTC
Labels: bug

**Comment by mikehuebner** [comment] 2023-09-10 02:56
I'm sadly also seeing the `redefinition` bug, just using the latest Expo and running `expo build` for iOS. Implementation isn't anything special, I'm going to try on a fresh app and see if I can reproduce. Lost a couple days on this already 😭

**Comment by 1abhishekpandey** [comment] 2023-09-10 08:49
Hey @mikehuebner,
If you encounter the same error on a fresh app, please provide a minimal reproducible example, and we will certainly investigate this further.

**Comment by mikehuebner** [comment] 2023-09-11 17:01
Spent a bit longer digging into this trying to figure out the root. I'll try getting an example repo put together today.

**Comment by 1abhishekpandey** [comment] 2023-09-11 17:14
I kindly request that you open a new issue once the example repository is prepared.

**Comment by mikehuebner** [comment] 2023-09-11 18:09
Here you go 😄 
https://github.com/rudderlabs/rudder-sdk-react-native/issues/243
